### ISSUE TITLE
QR code for OTP

### ISSUE THREAD

**Issue by Mahos-H** [Mahos-H/otp-generator#4]

**Comment by Mahos-H** [comment]
Now, to edit this, go to the page.js file present in the "generator" sub-directory of "src/app" and make your changes there. Simply add an extra option to convert the generated OTP to a QR code, and update receiving logic in page.js of "receiver" sub-directory to take QR-codes as input as well through webcam and decode them.

**Comment by sinpea** [comment]
Interested in working on this issue.
